version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_springbatch
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spectateur_db
      POSTGRES_USER: spec_user
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
