spring.application.name=project-springbatch

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/spectateur_db
spring.datasource.username=spec_user
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate=WARN

# Also disable Spring Data logging
logging.level.org.springframework.jdbc=WARN
logging.level.org.springframework.data=WARN

# Show only your application logs
logging.level.org.match=INFO

# Additionally, disable SQL in JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
